name: Exawind-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18.2
      with:
        source: './app ./src'
        exclude: '.'
        extensions: 'H,h,cpp'
        clangFormatVersion: 18
  CPU:
    needs: Formatting
    runs-on: ubuntu-latest
    container:
      image: ecpe4s/exawind-snapshot
      env:
          EXAWIND_MANAGER: /exawind-manager
          E4S_MACHINE: true
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Tests
        run: |
          /bin/bash -c " \
            source ${EXAWIND_MANAGER}/start.sh && \
            spack-start && \
            mkdir -p ${EXAWIND_MANAGER}/environments/exawind && \
            cd ${EXAWIND_MANAGER}/environments/exawind && \
            ln -s ${GITHUB_WORKSPACE} exawind && \
            spack -e e4s-build config add view:true && \
            spack -e e4s-build add cmake^zlib-ng~new_strategies && \
            spack -e e4s-build concretize -f && \
            quick-create-dev -s exawind@master && \
            spack manager external ${EXAWIND_MANAGER}/environments/e4s-build --exclude exawind && \
            spack concretize -f && \
            spack install && \
            spack cd -b exawind && \
            spack build-env exawind ctest -j $(nproc) --output-on-failure \
          "
