name: Exawind-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: './app ./src'
        exclude: '.'
        extensions: 'H,h,cpp'
        clangFormatVersion: 20
  CPU:
    needs: Formatting
    runs-on: ubuntu-24.04
    container:
      image: ecpe4s/exawind-snapshot
      env:
          EXAWIND_MANAGER: /exawind-manager
          E4S_MACHINE: true
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Tests
        run: |
          /bin/bash -c " \
            source ${EXAWIND_MANAGER}/start.sh && spack-start && \
            spack env activate e4s-build && \
            cd ${EXAWIND_MANAGER}/environments/e4s-build && \
            ln -s ${GITHUB_WORKSPACE} exawind && \
            spack develop --no-clone exawind@=master && \
            spack concretize -f && \
            spack install && \
            spack cd -b exawind && \
            spack build-env exawind ctest -j $(nproc) -LE no-ci --output-on-failure \
          "
