name: Exawind-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './app ./src'
        exclude: '.'
        extensions: 'H,h,cpp'
        clangFormatVersion: 13
  CPU:
    needs: Formatting
    runs-on: ubuntu-latest
    container:
      image: ecpe4s/exawind-snapshot
      env:
          SPACK_MANAGER: /spack-manager
          E4S_MACHINE: true
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Tests
        run: |
          /bin/bash -c " \
            source ${SPACK_MANAGER}/start.sh && \
            quick-create -n ci -s exawind@master && \
            spack cd -e && \
            ln -s ${GITHUB_WORKSPACE} exawind && \
            spack develop exawind@master && \
            spack manager external --latest --blacklist gmake exawind
            spack install && \
            spack cd -b exawind && \
            spack build-env exawind ctest -j $(nproc) --output-on-failure \
          "
